### ISSUE TITLE
Matter Fabricator

### ISSUE THREAD

**Issue by Servovicis** [Wurmatron/WurmTweaks#103]
Matter Fabricator works on SP, but when attempting to use it on the server it goes from 0% to 1%, then down to -1% and back up to 0% in a loop.

**Comment by Wurmatron** [comment]
I have had the same issue with an aesu. Think its an bug with techreborn

**Comment by Servovicis** [comment]
Not surprising, Tech Reborn seems to have quite a few of them.

**Comment by Wurmatron** [comment]
Unsure if this is fixed, server side but... Tech reborn got an update + its working in SSP
