### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by dodancs** [Wurmatron/WurmTweaks#105]
Technic pack launcher says can;t download and spits out url and it points to https://dl.dropboxusercontent.com/u/159385413/technic-0.7.3.zip which says E404. Fix plz?

**Comment by Wurmatron** [comment]
Oh thx i guess i forgot to update it too 0.7.4

**Comment by Wurmatron** [comment]
Will update in a few hours  when i get access to a computer
You can allways use ftb pack code: wurmcraft

**Comment by Wurmatron** [comment]
Updated technic link to 0.7.4
https://dl.dropboxusercontent.com/u/159385413/technic-0.7.4.zip
