### ISSUE TITLE
can't download wurmcraft ultimate 0.75

### ISSUE THREAD

**Issue by J1STAR** [Wurmatron/WurmTweaks#109]
I want to play this modpack.
Can you email me this modpack?
my email address : j.1star.0726@gmail.com

**Comment by Wurmatron** [comment]
Can Download via Technic or FTB, Technic can go down every once in a while though. A direct link to download the modpack via [dropbox in technic format](https://dl.dropboxusercontent.com/content_link/zIjfcorzcCsBCeyKu2le9U0VD8rLG4emCI4upEuI6XSq7E58mIvjU60wrSMWBNdc/file?dl=1), The best way to play Wurmcraft Ultimate is via the FTB Launcher using the packcode: "Wurmcraft" For more information about the pack check out https://forum.feed-the-beast.com/threads/1-7-10-wurmcraft-tfc-tech-reborn-wurmtweaks.111088/

**Comment by J1STAR** [comment]
dropbox link is 404 and modpack is not exist in ftb launcher.

2017-08-17 6:17 GMT+09:00 Wurmatron <notifications@github.com>:

**Comment by Wurmatron** [comment]
The dropbox link works however latter on today i can upload to web server

**Comment by Wurmatron** [comment]
FTB packcode is for the ftb launcher not the twitch / curse launcher

**Comment by Wurmatron** [comment]
Going to take a little bit longer than i thought due to web server security, feel free to join discord and i can help you with this issue

Edit: Should be up by tonight

**Comment by Wurmatron** [comment]
Direct Download: https://www.wurmcraft.com/assets/uploads/files/technic-0.7.5.zip
