### ISSUE TITLE
Tinkers tool interaction with TFC

### ISSUE THREAD

**Issue by Servovicis** [Wurmatron/WurmTweaks#12]
Tinkers tools dont interact properly with many of TFC components. Lumber axes dont chop tfc trees. Shovels dont work on charcoal. Hammers and excavators dig the row of, but gravity hits before taking out he full 3x3.

**Comment by Wurmatron** [comment]
hammers work with tfc and as for the axes this is to to tinkers not using an actual axe and tfc not even using the actual axe. *(Nether extend ItemAxe) it is fixable however due to tfc using ore dictionary for its axes
