### ISSUE TITLE
Compressed Cobblestone Recipes

### ISSUE THREAD

**Issue by Servovicis** [Wurmatron/WurmTweaks#18]
There is no recipe for Octuple Compressed Cobble

Shapeless Recipes:
Cobble x 9 crafts Double Compressed
Double Compressed x1 crafts Triple Compressed
Triple Compressed x1 crafts Quadruple Compressed
Quadruple Compressed x1 crafts Quintuple Compressed
Quintuple Compressed x1 crafts Sextuple Compressed
Sextuple Compressed x1 crafts Septuple Compressed

Compresses Recipes
Septupple x9 in Compresser = 1 Sextuple
Sextuple x9 in Compresser = 1 Quintuple 
Quintuple x9 in Compresser = 1 Quadruple 
Quadruple x9 in Compresser = 1 Triple 
Triple x9 in Compresser = 1 Double 

Smelting Recipes
Stone x1 smelts to Compressed Cobblestone x1 Except in Redstone Furnace (which takes 9)

**Comment by Wurmatron** [comment]
Fixed Next Update
