### ISSUE TITLE
Missing Recipes

### ISSUE THREAD

**Issue by Servovicis** [Wurmatron/WurmTweaks#22]
Creating a list of missing or broken recipes.
Machine Frame(all tiers) - Thermal Expansion
Water Wheel Segment - Immersive Engineering
Windmill Blade - Immersive Engineering
Improved Windmill Blade - Immersive Engineering

**Comment by Servovicis** [comment]
Recipe to craft items in order to start Botania require terasteel, an item obtained  at the end of Botania.
Recipe for Galacticraft Rockets require Titanium

**Comment by Servovicis** [comment]
Item Conduits - EnderIO Recipe says ender Fluid Conduits, but the meta data isn't assigned to an item.

**Comment by Servovicis** [comment]
Some of the Cobblestone to rock recipes match cobblestone to button recipes

**Comment by Servovicis** [comment]
Meat Pallet from Wurmtweeks doesn't have a recipe.

**Comment by Servovicis** [comment]
Refined Cheese cant be crafted with its recipe as there is only one cheese item so it just combines on itself.

**Comment by Servovicis** [comment]
Compressor recipe 4:1 to increase gem tier broken  (Intended?)
Macerator/Sagmill/Pulveriser Recipe 1:4 to lower tier gem broken (Intended?)

**Comment by Servovicis** [comment]
Steel Pick can not be casted from tinkers smeltery.

**Comment by Wurmatron** [comment]
there we go.

**Comment by Wurmatron** [comment]
Unstable Ingots

**Comment by Servovicis** [comment]
InndustrialCraft BatBox

**Comment by Servovicis** [comment]
Transistors and Microchips from Opencomputers (all tiers)

**Comment by Servovicis** [comment]
Red Alloy WIre

**Comment by Wurmatron** [comment]
Straw

**Comment by Wurmatron** [comment]
Iridium Alloy (NO TITANIUM)!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Wurmatron** [comment]
Mekanism Machine recipes

**Comment by Wurmatron** [comment]
magic pencil, crayan

**Comment by Wurmatron** [comment]
brewing

**Comment by Wurmatron** [comment]
silicon

**Comment by Wurmatron** [comment]
vat

**Comment by Wurmatron** [comment]
Nether wart

**Comment by Wurmatron** [comment]
All Fixed

**Comment by Servovicis** [comment]
Tinkers:
Silky Gem
Obsidian Large Plate
Lava Crystal
Arrowhead Cast (Crashes Game when trying to view recipe)
Shuriken head cast (Material set at 8 ingots from .5)

**Comment by Servovicis** [comment]
Tessaract Frame to full

**Comment by Servovicis** [comment]
<img width="960" alt="titanium" src="https://cloud.githubusercontent.com/assets/3997657/16817613/32d77320-4909-11e6-8043-b7d2fc654b03.png">

**Comment by Wurmatron** [comment]
Silky Gem no same for Lava Crystal
