### ISSUE TITLE
Tech Reborn (and tech rant in general)

### ISSUE THREAD

**Issue by legitairsoft123** [Wurmatron/WurmTweaks#3]
_before reading: I know wurm is rebalancing recipes, but I need to say this just in case the problems arise again_
Tech reborn needs rebalancing, basic machines require you visit mars, when in reality they should be after IC2. This is one of the main problems I have with this pack, whenever you (wurm) see a mod or recipe that should be harder than early game machines (ie. Tech reborn, immersive engineering[should be early game], forestry, etc) you put it at very end game instead of where it belongs at mid-game. This makes progression through the pack very choppy. TFC is perfect for the first thing you do (I really liked how you could start extremely basic machines before you finished TFC like in gregtech with the bronze machines, but i'm also ok with having to finish TFC before starting machines), then when you move on to post TFC and into Thermal Expansion it is also ok (a bit of a jump, but, ok nonetheless). However when you finish up with TE and IC2 you hit the infamous "wall", a figurative void of nothingness. You see where you are now, and you then look off into the future, and it seems like an unreachable goal. I remember hitting this wall when wurm owned his own server, and I hated it. There didn't seem like there was any reason to play anymore and I simply didn't. I got off for a few months until got bored and tried wurmcraft again, for about a week until i quit again. I really enjoy this modpack and I would hate to grow bored of it and leave again. To recap, early game is awesome middle game needs major work and end game... well no one has ever reached end game, not even the modpack creater himself. Some may think that's a good thing, but a game with an unreachable goal isn't one I'm looking forward to playing.

**Comment by Wurmatron** [comment]
shortened version plz

**Comment by legitairsoft123** [comment]
fix tech

**Comment by Wurmatron** [comment]
should be fixed after the recipe rewrite
