### ISSUE TITLE
LambdaLib

### ISSUE THREAD

**Issue by qvmc** [Wurmatron/WurmTweaks#34]
When downloading the recommended version (0.7.1 on the FTB launcher), you have to update LambdaLib manually. It has version 1.2.0 installed, but it needs 1.2.1. Its not that much of a problem, but its annoying and eazy to fix.

**Comment by Wurmatron** [comment]
Confirmed, in Technic and FTB release.

**Comment by Wurmatron** [comment]
Should be fixed within the next few hours on 0.7.2 release
