### ISSUE TITLE
Game Crash with Arrowhead Cast

### ISSUE THREAD

**Issue by Servovicis** [Wurmatron/WurmTweaks#36]
Looking at the Arrowhead Cast(hoverover/hold in inventory) causes the game to crash. Item can exist in inventory just fine until its selected, when dropped disappears immediately, and when the tooltip would show up instead the game crashes. NEI lets you see the item, but if you look at the recipe to make or use it the game will also crash.

**Comment by Wurmatron** [comment]
Problem with Mantle API for tinkers atm im unsure if i can release an fix for this.

**Comment by Wurmatron** [comment]
kk its fine as long as we know that its an custom build and dont report errors too them.  
To get the fix: https://db.tt/maXkRJYp
