### ISSUE TITLE
Bow Issues

### ISSUE THREAD

**Issue by legitairsoft123** [Wurmatron/WurmTweaks#4]
can't fire TFC bow unless you have both types of arrows in your inventory

**Comment by Wurmatron** [comment]
Seems to be a bug with tfc it self. I am not responsible for bugs in tfc. i will look into a fix if i get some time though.

**Comment by Wurmatron** [comment]
This is an an tfc but its an bug with the server software kcaldren, This is unfixable without an ton of work so im going to consider this not fixable and close it.
