### ISSUE TITLE
More missing Recipes List

### ISSUE THREAD

**Issue by Servovicis** [Wurmatron/WurmTweaks#41]
Starting off with Conduit Bindings from EnderIO, used in 6 or so recipes still down from many more. Trying to phase these out?

3 tiers of Capacitor Banks from Ender IO. (Battery, that is also used to upgrade darksteel armor)(Deprecated version is craftable)

**Comment by Wurmatron** [comment]
this is annoying due to using nbt and meta to change the items type

**Comment by Wurmatron** [comment]
greate wood log

**Comment by Servovicis** [comment]
Metal Credits to Ingot is broken.

**Comment by Servovicis** [comment]
Universal Fluid Cell (IC2) has no recipe (used in 1 recipe for a generator, among being the mobile fluid storage for that mod. (usually costs tin ingot x4  for 4 of them, if I recall)

**Comment by Wurmatron** [comment]
Mostly fixed on next update

**Comment by Servovicis** [comment]
Open Blocks Recipes missing order of use for mod:
Required:
MicroController
Disk Platter
Numeric Keypad
Control Unit
Memory(Tier 1-3.5)
EEPROM(LUA Bios)
------------------------------
Used Often:
Screen(Tier II)
Arithmetic Logic Unit
Accelerated Processing Unit(Tiers I and II)
Redstone Card
Access Point
World Sensor Card
Relay
Data Card (Tier I - III)
Network Card
------------------------------
Used, but not much:
Waypoint
Terminal Server
Rack
Disk Drive
Net Splitter
Transposer

------------------------------
Not Currently used for anything best I can tell:
Printed Circuit Board
Raw Circuit Board
Hover Upgrade(Tier I,II)
Trading Upgrade
