### ISSUE TITLE
Open Modular Turrets

### ISSUE THREAD

**Issue by Servovicis** [Wurmatron/WurmTweaks#42]
Not everything listed I imagine would or should be implemented, but a full list of items that don't have a recipe.

The Chambers for the turrets don't have recipes, making them impossible to craft.

Recipes Missing:
Power Base Expander Tier 1-5
Base Inventory Expander Tier 1-5
Incendiary Turret
Blazing Clay
Relativistic Turret
Teleporter Turret
Basic Turret Base Crank
Upgrade-Scattershot
Addon-Recycler
Addon-Turret Concealer
Addon-Potentia Converter
Addon-Serial Port
Barrel Tier 2-4
Chamber Tier 2-5
All the walls/Fence

**Comment by Wurmatron** [comment]
Added a few of the recipes. but some of these items should not have an recipe at all
