### ISSUE TITLE
Missing Recipes: Open Computers Edition

### ISSUE THREAD

**Issue by Servovicis** [Wurmatron/WurmTweaks#43]
Open Blocks Recipes missing order of use for mod:
Required:
MicroController
Disk Platter
Numeric Keypad
Control Unit
Memory(Tier 1-3.5)
EEPROM(LUA Bios)

---

Used Often:
Screen(Tier II)
Arithmetic Logic Unit
Accelerated Processing Unit(Tiers I and II)
Redstone Card
Access Point
World Sensor Card
Relay
Data Card (Tier I - III)
Network Card

---

Used, but not much:
Waypoint
Terminal Server
Rack
Disk Drive
Net Splitter
Transposer

---

Not Currently used for anything best I can tell:
Printed Circuit Board
Raw Circuit Board
Hover Upgrade(Tier I,II)
Trading Upgrade

**Comment by Wurmatron** [comment]
This issue / recipes will be fixed within the next release of the modpack.
