### ISSUE TITLE
Disappearing recipes

### ISSUE THREAD

**Issue by xenofighter** [Wurmatron/WurmTweaks#45]
Since the update into .7.2v several previously working recipes, such as those used with a furnace (including all forms of stones so far encountered) are not registered, and are not recognized by the NEI nor the furnace itself.

**Comment by Wurmatron** [comment]
would need an list of these "Disappearing" recipes. This is due to changing code constantly and sometimes i accidentally delete things without meaning too.

**Comment by Wurmatron** [comment]
This issue / recipes will be fixed within the next release of the modpack.

I Have fixed Cobble - > Stone Smelting, If there is anything else, feel free to open another issue to let me know of more broken recipes
