### ISSUE TITLE
Request to remove Sticky Buff From Infernal Mobs

### ISSUE THREAD

**Issue by Servovicis** [Wurmatron/WurmTweaks#48]
Config option change requested in Infernal Mobs config for line
B:"MM_Sticky enabled"=true
to be changed to 
B:"MM_Sticky enabled"=false.

The mobs are next to unkillable as is. Having our weapons stolen from them, getting killed by our own weapon, and then them despawning when we respawn is frustrating.

**Comment by Wurmatron** [comment]
This issue / recipes will be fixed within the next release of the modpack.
