### ISSUE TITLE
coke oven

### ISSUE THREAD

**Issue by legitairsoft123** [Wurmatron/WurmTweaks#5]
the coke oven is too expensive for the purpose it has. recipe should be red/blue steel sheets/dsheets instead of the mixed sheet. The only purpose i could see for having the coke oven be so expensive is that you can make charcoal from it, however, its a very slow process and you could just as easily made a redstone furnace that would be cheaper. making the recipe cheaper would allow the player to try some of the early game immersive engineering options without changing the recipes immensely.

**Comment by Wurmatron** [comment]
will lower it in the tech tree a little to around steel to black steel age

**Comment by Wurmatron** [comment]
Here is the recipe in the 0.7 update

![Coke Oven Recipe](http://i.imgur.com/CO3bM9p.png)
