### ISSUE TITLE
Item Dupe

### ISSUE THREAD

**Issue by Servovicis** [Wurmatron/WurmTweaks#50]
When you have Soulbound on armor while keep inventory is on, the armor will try and duplicate itself in the slot below it, due to TFC changing the back slot to take the first armor inventory slot id. This can cause items to either become copies, or items to be lost. Seems to only affect equipped armor.

**Comment by Wurmatron** [comment]
Removed Soul Bound Enchantments
This issue / recipes will be fixed within the next release of the modpack.
