### ISSUE TITLE
Tech Reborn Alloy Furnace

### ISSUE THREAD

**Issue by Servovicis** [Wurmatron/WurmTweaks#54]
All Furnace recipes are broken for Tech Reborn Alloy Furnace

This also makes red alloy uncraftable as its the only furnace that shows a recipe.

**Comment by Wurmatron** [comment]
Seems to be caused by Alloy Smelter built in Ore Dictionary, this will require an lot of work to fix.

**Comment by Servovicis** [comment]
Anything that doesn't require that level of tech tree could be moved to other alloy methods like induction furnace and Alloy Smelter. Stuff like redwire alloy

**Comment by Wurmatron** [comment]
This issue / recipes will be fixed within the next release of the modpack.
