### ISSUE TITLE
Open Computers

### ISSUE THREAD

**Issue by Servovicis** [Wurmatron/WurmTweaks#56]
Raw Circuit Board is required for Accelerated Processing Unit Tier II, but seemingly has no recipe itself.
EEPROM (LUA BIOS) doesn't have a recipe, just the EEPROM.
Memory made in Assembling Machine, which is post space due to titanium hull in recipe. Intentional?

**Comment by Servovicis** [comment]
Recipe for the Ender IO Network Conduit for Open Computers

**Comment by Wurmatron** [comment]
This issue / recipes will be fixed within the next release of the modpack.
