### ISSUE TITLE
Extra Cells Recipes.

### ISSUE THREAD

**Issue by Servovicis** [Wurmatron/WurmTweaks#58]
Super-Laminiar Fluiduct from Thermal Dynamics  has no recipe, making the ME Fluid Interface Uncraftable

ME Fluid Terminal Recipe Includes ME Fluid Bus, which requires ME Fluid Terminal.

Several of the Buses have no recipes.

**Comment by Wurmatron** [comment]
This issue / recipes will be fixed within the next release of the modpack.
