### ISSUE TITLE
rubber

### ISSUE THREAD

**Issue by legitairsoft123** [Wurmatron/WurmTweaks#6]
how do you get rubber trees/rubber? iirc last wurmcraft rubber trees spawn randomly along forests, but I haven't seen any yet. Are they in a certain area/climate or are they just not added yet?

**Comment by Wurmatron** [comment]
Till this is resoled i added rubber sapling to admin shop

**Comment by Wurmatron** [comment]
IC2 Ruber trees confirmed to spawn in 0.7 (Still rare)
