### ISSUE TITLE
Grout --> Seared Bricks

### ISSUE THREAD

**Issue by Phantom329** [Wurmatron/WurmTweaks#7]
I made some grout but I can't smelt it in a furnace or melt it in a crucible. Is that a bug or how do we get the bricks?

**Comment by legitairsoft123** [comment]
its a bug, a furnace recipe will be added soon

**Comment by Wurmatron** [comment]
should also be fixed on the recipe rework.

**Comment by Wurmatron** [comment]
Fixed as of 0.7 update
