### ISSUE TITLE
Fix speed on Sub Girls Mod

### ISSUE THREAD

**Issue by Servovicis** [Wurmatron/WurmTweaks#71]

**Comment by Wurmatron** [comment]
why can't they go mach 25?

**Comment by Servovicis** [comment]
Seems this issue also affects some Eldritch Constructs, all the Dryads.

**Comment by Wurmatron** [comment]
May be fixed next update

**Comment by Wurmatron** [comment]
This issue / recipes will be fixed within the next release of the modpack.
