### ISSUE TITLE
Insulated tin cable from IC has different rubber requirement

### ISSUE THREAD

**Issue by ronsardis** [Wurmatron/WurmTweaks#78]
Insulated tin cable (4959:13) has different rubber requirement from copper (4959), gold (4959:3), and HV (4959:6) insulated cable in IC.
Suggest changing all recipes to work with all three kinds of rubber (raw rubber, rubber bar, and IC Rubber).

**Comment by Wurmatron** [comment]
This issue / recipes will be fixed within the next release of the modpack.
