### ISSUE TITLE
Feature request: Add recipes to change gem type

### ISSUE THREAD

**Issue by ronsardis** [Wurmatron/WurmTweaks#79]
Possible handy feature request.  It is a bit annoying that there are so many types of gems.  Suggestion is that if you put a gem into crafting grid it would be able to be crafted into the next gem type in sequence by item number.
So a chipped ruby (4222) would craft into a chipped sapphire (4223) and a chipped sapphire into a chipped emerald (4224).  This would allow for a more fluid gem upgrading experience.

**Comment by Wurmatron** [comment]
I have considered adding mixed gems but it will recipe almost all gem recipes to be reworked to allow for the use of them. This way it can still stay balanced due to some recipes requiring special gems and the ones that do not care can use "Mixed Gems"

**Comment by Wurmatron** [comment]
This issue / recipes will be fixed within the next release of the modpack.
