### ISSUE TITLE
TFC Hoppers are broken

### ISSUE THREAD

**Issue by Phantom329** [Wurmatron/WurmTweaks#8]
TFC hoppers do not function at all. A temporary solution would be to make a trade at spawn or just change the recipe to make MC ones instead.

**Comment by legitairsoft123** [comment]
hoppers don't work with most TFC things, but they are the same as vanilla iirc

**Comment by Wurmatron** [comment]
i dont know what they "dont work", but i will if i can remember to change it so the recipe rework does not require a player to have an assembling machine to create the vanilla  hopper

**Comment by Wurmatron** [comment]
next update the recipe is the same as the regular hopper just replaced with the TFC items
