### ISSUE TITLE
Unable to make wurmtweaks pick cast with smithed pick heads

### ISSUE THREAD

**Issue by ronsardis** [Wurmatron/WurmTweaks#82]
I was trying to make a pick cast with a smithed black bronze and a smithed steel pick head and it wouldn't work.  I then tried with a pick head made with a mold in the fluid transposer and it could be used to make a cast.

My guess is that the data for blacksmithing bonus on tools in TFC is an NBT data value and that the casting recipe for the casts in Wurmtweaks in NBT specific and therefore it cannot use an item with a smithing bonus on it.

**Comment by Wurmatron** [comment]
Its thats the cast its unfixable
